version: '2'

services:
    puffin:
        build: .
        image: puffinrocks/puffin
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
           # - .:/usr/src/app
        depends_on:
            - puffindb
        ports: 
            - "8080:8080"
        environment:
            - SERVER_NAME=beta.jenca.org
            - VIRTUAL_HOST=beta.jenca.org
            - VIRTUAL_PORT=8080
            - SECRET_KEY=generated-secret
            - SECURITY_REGISTERABLE=True
            - MAIL_SUPPRESS_SEND=True
           # - MAIL_SERVER=<smtp-server>
           # - MAIL_PORT=<smtp-port>
           # - MAIL_USERNAME=<smtp-login>
           # - MAIL_PASSWORD=<smtp-password>
           # - MAIL_DEFAULT_SENDER=Puffin <sender-address>
           # - MAIL_USE_TLS=False
           # - MAIL_USE_SSL=False
        networks:
            - front
            - back
            - default

    puffindb:
        image: postgres
        ports:
            - 5432
        volumes:
            - ./postgresData:/var/lib/postgresql/data
        networks:
            back:

networks:
    
    front:
    back:
