version: '2'

services:
    puffin:
        build: .
        image: puffinrocks/puffin
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
           # - .:/usr/src/app
        depends_on:
            - puffindb
        ports: 
            - "8080:8080"
        environment:
            - SERVER_NAME=beta.jenca.io
            - VIRTUAL_HOST=beta.jenca.io
            - VIRTUAL_PORT=8080
            - SECRET_KEY=mylovelyhorse
            - SECURITY_REGISTERABLE=True
            - MAIL_SUPPRESS_SEND=False
            - MAIL_SERVER=smtp.mailgun.org
            - MAIL_PORT=2525
            - MAIL_USERNAME=postmaster@mail.jenca.io
            - MAIL_PASSWORD=93cec017799c33ddaf9cd56d3ca9daae
            - MAIL_DEFAULT_SENDER=john@jenca.io
            - MAIL_USE_TLS=True
            - MAIL_USE_SSL=False
        networks:
            - front
            - back
            - default

    puffindb:
        image: postgres
        ports:
            - 5432
        volumes:
            - ./postgresData:/var/lib/postgresql/data
        networks:
            back:

networks:
    
    front:
    back:
